### ISSUE TITLE
Allowed by onvista?

### ISSUE THREAD

**Issue by MaximilianClemens** [ThisIsBenny/Onvista-Share-Price-API#1]
Hi @ThisIsBenny,

do you know if it is allowed to use the API of onvista or could this follow any legal problems?

Regards
Max

**Comment by ThisIsBenny** [comment]
Hi @MaximilianClemens i have checked in der past the AGB and didn't find a clear answer on this. But I'm also not an expert on this. You should not use the data for commercial purpose and should not produce a high load on the Site. 

Regards Benny

**Comment by MaximilianClemens** [comment]
Hi,

I found an answer at https://www.onvista.de/disclaimer.html
"Eine automatisierte Abfrage der Inhalte des Finanzportals ist ohne ausdrückliche Einwilligung von onvista in jeglicher Form unzulässig. Zuwiderhandlung wird verfolgt."

Sounds not that good :/

Regards
Maximilian
